### ISSUE TITLE
Node crashing before validation

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-go#1035]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x225d3b0]

goroutine 1 [running]:
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips.func1({0xe9, 0xed, 0x2a, 0x37, 0xbb, 0x85, 0xa9, 0x2d, 0x61, 0x59, ...}, ...)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:704 +0x50
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips.func3({{0xe9, 0xed, 0x2a, 0x37, 0xbb, 0x85, 0xa9, 0x2d, 0x61, 0x59, ...}, ...})
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:733 +0xf9
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips.func4({0xc0016071a0, 0xc002475110, 0xc002475138}, {0xc00314a1e0, 0x5c, 0x5c})
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:761 +0x215
github.com/cosmos/iavl.(*ImmutableTree).IterateRange.func1(0xc002475150)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20211223100228-a33b117aa31e/immutable_tree.go:187 +0x43
github.com/cosmos/iavl.(*Node).traverseInRange(0xc001b4d540, 0xc002475210, {0xc0039e4618, 0x15, 0x18}, {0xc0039e4630, 0x18, 0xc00385b538}, 0xe0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20211223100228-a33b117aa31e/node.go:461 +0x13c
github.com/cosmos/iavl.(*ImmutableTree).IterateRange(0xc002567980, {0xc0039e4618, 0x10, 0x7}, {0xc0039e4630, 0xc001f67520, 0xc0025ce9b0}, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20211223100228-a33b117aa31e/immutable_tree.go:185 +0x78
github.com/idena-network/idena-go/core/state.(*ImmutableTree).IterateRange(...)
        /home/runner/work/idena-go/idena-go/core/state/tree.go:220
github.com/idena-network/idena-go/core/state.(*StateDB).IterateIdentities(0xc002558180, 0xc003a0e090)
        /home/runner/work/idena-go/idena-go/core/state/statedb.go:1206 +0x179
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips(0xc001db2360, 0x1)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:750 +0x3a5
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).calculateCeremonyCandidates(0xc001db2360, 0x60)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:547 +0x79
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).restoreState(0xc001db2360)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:333 +0x15f
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).Initialize(0xc001db2360, 0xb19af268b25dbc81)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:199 +0x4fc
github.com/idena-network/idena-go/node.(*Node).StartWithHeight(0xc001db2480, 0x0)
        /home/runner/work/idena-go/idena-go/node/node.go:304 +0x6ab
github.com/idena-network/idena-go/node.(*Node).Start(...)
        /home/runner/work/idena-go/idena-go/node/node.go:261
main.main.func1(0xc0000ba2c0)
        /home/runner/work/idena-go/idena-go/main.go:109 +0x265
github.com/urfave/cli.HandleAction({0x2404b80, 0x3390e80}, 0xc0000bcc40)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.(*App).Run(0xc0000bcc40, {0xc000122150, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:286 +0x625
main.main()
        /home/runner/work/idena-go/idena-go/main.go:114 +0x612
```

happens with 0.30.1

**Comment by reb0rn21** [comment]
My log:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x225d3b0]
​
goroutine 1 [running]:
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips.func1({0xe9, 0xed, 0x2a, 0x37, 0xbb, 0x85, 0xa9, 0x2d, 0x61, 0x59, ...}, ...)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:704 +0x50
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips.func3({{0xe9, 0xed, 0x2a, 0x37, 0xbb, 0x85, 0xa9, 0x2d, 0x61, 0x59, ...}, ...})
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:733 +0xf9
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips.func4({0xc005b9a258, 0xc004367110, 0xc004367138}, {0xc004e1aae0, 0x5c, 0x5c})
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:761 +0x215
github.com/cosmos/iavl.(*ImmutableTree).IterateRange.func1(0xc0049f9150)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20211223100228-a33b117aa31e/immutable_tree.go:187 +0x43
github.com/cosmos/iavl.(*Node).traverseInRange(0xc0046b0fa0, 0xc004367210, {0xc0065ffb00, 0x15, 0x18}, {0xc0065ffb18, 0x18, 0xc0065ed4c0}, 0xe0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20211223100228-a33b117aa31e/node.go:461 +0x13c
github.com/cosmos/iavl.(*ImmutableTree).IterateRange(0xc004dfcae0, {0xc0065ffb00, 0x10, 0x7}, {0xc0065ffb18, 0xc0065b8d90, 0xc0065b9960}, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20211223100228-a33b117aa31e/immutable_tree.go:185 +0x78
github.com/idena-network/idena-go/core/state.(*ImmutableTree).IterateRange(...)
        /home/runner/work/idena-go/idena-go/core/state/tree.go:220
github.com/idena-network/idena-go/core/state.(*StateDB).IterateIdentities(0xc0046d5e00, 0xc006858f30)
        /home/runner/work/idena-go/idena-go/core/state/statedb.go:1206 +0x179
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips(0xc0046c5440, 0x1)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:750 +0x3a5
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).calculateCeremonyCandidates(0xc0046c5440, 0x0)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:547 +0x79
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).restoreState(0xc0046c5440)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:333 +0x15f
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).Initialize(0xc0046c5440, 0xb19af268b25dbc81)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:199 +0x4fc
github.com/idena-network/idena-go/node.(*Node).StartWithHeight(0xc0046c5560, 0x0)
        /home/runner/work/idena-go/idena-go/node/node.go:304 +0x6ab
github.com/idena-network/idena-go/node.(*Node).Start(...)
        /home/runner/work/idena-go/idena-go/node/node.go:261
main.main.func1(0xc00017adc0)
        /home/runner/work/idena-go/idena-go/main.go:109 +0x265
github.com/urfave/cli.HandleAction({0x2404b80, 0x3390e80}, 0xc0001681c0)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.(*App).Run(0xc0001681c0, {0xc00004e080, 0x4, 0x4})
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:286 +0x625
main.main()
        /home/runner/work/idena-go/idena-go/main.go:114 +0x612`

**Comment by pocoloko** [comment]
This is the very first error in my logs when the node crashed: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x225d3b0]

goroutine 161025656 [running]:
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips.func1({0xe9, 0xed, 0x2a, 0x37, 0xbb, 0x85, 0xa9, 0x2d, 0x61, 0x59, ...}, ...)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:704 +0x50
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips.func3({{0xe9, 0xed, 0x2a, 0x37, 0xbb, 0x85, 0xa9, 0x2d, 0x61, 0x59, ...}, ...})
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:733 +0xf9
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips.func4({0xc0161f2c30, 0xc003310820, 0xc010c81848}, {0xc0124510e0, 0x5c, 0x5c})
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:761 +0x215
github.com/cosmos/iavl.(*ImmutableTree).IterateRange.func1(0xc010c81860)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20211223100228-a33b117aa31e/immutable_tree.go:187 +0x43
github.com/cosmos/iavl.(*Node).traverseInRange(0xc00293f360, 0xc003310920, {0xc0029df7d0, 0x15, 0x18}, {0xc0029df830, 0x18, 0xc036e51a88}, 0xe0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20211223100228-a33b117aa31e/node.go:461 +0x13c
github.com/cosmos/iavl.(*ImmutableTree).IterateRange(0xc00b044180, {0xc0029df7d0, 0x10000c003310960, 0x7f5e5c03ecb8}, {0xc0029df830, 0x30, 0x7f5e95211a68}, 0x30, 0xc0018a9c00)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20211223100228-a33b117aa31e/immutable_tree.go:185 +0x78
github.com/idena-network/idena-go/core/state.(*ImmutableTree).IterateRange(...)
        /home/runner/work/idena-go/idena-go/core/state/tree.go:220
github.com/idena-network/idena-go/core/state.(*StateDB).IterateIdentities(0xc00b004600, 0xc003a57c50)
        /home/runner/work/idena-go/idena-go/core/state/statedb.go:1206 +0x179
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).getCandidatesAndFlips(0xc00a715e60, 0x0)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:750 +0x3a5
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).calculateCeremonyCandidates(0xc00a715e60, 0xe9)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:547 +0x79
github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).asyncFlipLotteryCalculations(0xc00a715e60)
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:466 +0x65
created by github.com/idena-network/idena-go/core/ceremony.(*ValidationCeremony).handleFlipLotteryPeriod
        /home/runner/work/idena-go/idena-go/core/ceremony/ceremony.go:447 +0x1ef
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x225d3b0]
```
