### ISSUE TITLE
Raspberry Pi Idena

### ISSUE THREAD

**Issue by biterminator** [idena-network/idena-go#1109]
I am asking idena developers to release ARM version of idena that can run on Raspberry Pi 4 devices.
Alternative is to post instructions for how to do it manually.

**Comment by sidenaio** [comment]
Hello, try [v1.0.2-rc2](https://github.com/idena-network/idena-go/releases/tag/v1.0.2-rc2)

**Comment by illusiontorment** [comment]
Hey, guys!

I use a Pi4 (8gb ram) with ubuntu server 22.04.2 lts to run my Idena node.

As you can imagine, I have tremendous issues since the Corea HF.

I tried both rc-1 and rc-2, but to no avail. Even if my node manages to synchronize and I am able to turn on mining in the desktop app, sooner or later the node goes offline, and I get my due mining penalty :-)!

I don't know how significant the number of people using a Pi to mine Idena realolly is, but it is a very handy (and cost efficient) way of running a node. I sure hope that the dev(il)s come up with a solution for our issue. Thanx!

**Comment by hunagyp** [comment]
hi all,
same issue here. 
i also used rpi4 up until now. but it's not working anymore since 1.0.1 update...
if you drop the support, i'm out from the project. for me it was easy to run an idena node on a small raspi. but i'm not planning to pay for vps or other methods.
Is there any plan to keep the support of raspi4?

**Comment by kikimanito** [comment]
Same here, on  RaspberryPi 4 - Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1024-raspi aarch64).
Logs are filled with these errors
```
INFO [03-05|10:44:19.978] Wait for block proposal
ERROR[03-05|10:44:20.043] contract err                             err="Error calling the VM: compilation error: UnsupportedTarget(\"aarch64\")"
ERROR[03-05|10:44:20.083] Proposed block is not found              err="invalid block roots. Expected=13c25e5d61f937739e7bb0390529523c19eead447154f2fee115e579a1d94c4a & 1aff5e84b9510b8c4b55f02d597ace6b1058b7ebe83f60e688b50aab57f1715c, actual=c1f0483760d0c66f7ce2f473976a808bf3e1728a7b5e57ed0bd79c1d2772f422 & 1aff5e84b9510b8c4b55f02d597ace6b1058b7ebe83f60e688b50aab57f1715c"
```

**Comment by midenaio** [comment]
@kikimanito @hunagyp please specify your node version. Are you running [1.0.2-rc2](https://github.com/idena-network/idena-go/releases/tag/v1.0.2-rc2)?

**Comment by kikimanito** [comment]
@midenaio Yes, I'm running 1.0.2-rc2:
```
INFO [03-05|20:23:59.925] Consensus config transformed to          ver=11
INFO [03-05|20:23:59.926] Idena node is starting                   version=1.0.2-rc2
INFO [03-05|20:23:59.926] initial HTTP endpoint opened             url=http://0.0.0.0:9009 cors=* vhosts=localhost
```

**Comment by sidenaio** [comment]
@kikimanito, did you try idena-node-v1.0.2-rc2-linux-arm64.tar.gz?

**Comment by illusiontorment** [comment]
@sidenaio Can you please share where I can wget this .gz from? I'm kind of a total greenhorn when it comes to practically all of this, and all I can do is to follow recipies.

**Comment by hunagyp** [comment]
> @kikimanito @hunagyp please specify your node version. Are you running [1.0.2-rc2](https://github.com/idena-network/idena-go/releases/tag/v1.0.2-rc2)?

```
INFO [03-05|20:58:04.190] Idena node is starting                   version=1.0.2-rc1
INFO [03-05|20:58:04.191] initial HTTP endpoint opened             url=http://192.168.1.155:9009 cors=* vhosts=localhost
INFO [03-05|20:58:05.231] Start compacting DB
```
I updated yesterday evening to 1.0.2-rc1 (downloaded from from https://arm64.idena.net.ar/)
It looks like, there was no error in the node's log since then. And I'm still in "mining status" too, I was not kicked out overnight, yet.
For the record, this was my error in previous version

```
150217    INFO [03-03|09:18:03.000] Start loop                               round=5676294 head=0xf323b856d0f7e49e0f3f604496bdeb3c4556a464a8e904bfbeda13d015c0f210 shardId=1 p2p-shardId=0 total-peers=18 own-shard-peers=18 online-nodes=506 network=2170
150218    INFO [03-03|09:18:13.001] Selected proposer                        proposer=0x55Fd949e854479b1b10E2f8d633863C61fa408D3
150219    INFO [03-03|09:18:13.015] Wait for block proposal 
150220    ERROR[03-03|09:18:13.132] contract err                             err="Error calling the VM: compilation error: UnsupportedTarget("aarch64")"
150221    ERROR[03-03|09:18:13.132] Proposed block is not found              err="tx bloom is invalid"
```

**Comment by sidenaio** [comment]
@illusiontorment @hunagyp [idena-node-v1.0.2-rc2-linux-arm64.tar.gz](https://github.com/idena-network/idena-go/releases/download/v1.0.2-rc2/idena-node-v1.0.2-rc2-linux-arm64.tar.gz)

**Comment by illusiontorment** [comment]
@sidenaio Thanks! I'll be back with the news.

**Comment by illusiontorment** [comment]
@sidenaio version=0.0.1?

**Comment by illusiontorment** [comment]
![image](https://user-images.githubusercontent.com/39781336/223052326-74964636-ddc6-4027-97ea-0c2fa5d3adb3.png)
It managed to process 6 blocks and then crashed for some reason. Same as before.

**Comment by sidenaio** [comment]
@illusiontorment  Error calling the VM: compilation error: UnsupportedTarget("aarch64") ?

**Comment by illusiontorment** [comment]
Suprisingly, no.
![image](https://user-images.githubusercontent.com/39781336/223055789-5668da6d-e398-49b1-8648-a51710bc6117.png)

**Comment by illusiontorment** [comment]
Basically no error message. It simply stopped.

**Comment by hunagyp** [comment]
@illusiontorment check /var/log/syslog - I assume, there is the stack of the crash
@sidenaio I changed now to rc2 from the github link and i will wait, what happens with the node.
(with rc1, running from yesterday, it started to crash this morning like @illusiontorment said - without the "UnsupportedTarget" err. messsage. It crashed 2 times silently. Will see what happens with rc2 now.

**Comment by hunagyp** [comment]
btw, this was my stack (some headlines of it) with rc1 - logged in syslog

```
Mar  6 09:33:10 pi-server idena-node[214203]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
Mar  6 09:33:10 pi-server idena-node[214203]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar  6 09:33:10 pi-server idena-node[214203]: fatal runtime error: failed to initiate panic, error 1073881664
Mar  6 09:33:10 pi-server idena-node[214203]: SIGABRT: abort
Mar  6 09:33:10 pi-server idena-node[214203]: PC=0xffff93edf200 m=10 sigcode=18446744073709551610
Mar  6 09:33:10 pi-server idena-node[214203]: signal arrived during cgo execution
Mar  6 09:33:10 pi-server idena-node[214203]: goroutine 2825 [syscall]:
Mar  6 09:33:10 pi-server idena-node[214203]: runtime.cgocall(0x2319050, 0x4000a89818)
Mar  6 09:33:10 pi-server idena-node[214203]: #011/usr/local/go/src/runtime/cgocall.go:158 +0x54 fp=0x4000a896c0 sp=0x4000a89680 pc=0x1001084
Mar  6 09:33:10 pi-server idena-node[214203]: github.com/idena-network/idena-wasm-binding/lib._Cfunc_execute({0x4007867488, 0x4000ed4290, {0x2317ec8, 0x2317f30, 0x2317fc8, 0x2318050, 0x2318140, 0x23180d0, 0x23181b0, 0x2318220, ...}}, ...)
Mar  6 09:33:10 pi-server idena-node[214203]: #011_cgo_gotypes.go:393 +0x40 fp=0x4000a89810 sp=0x4000a896c0 pc=0x226dbe0
Mar  6 09:33:10 pi-server idena-node[214203]: github.com/idena-network/idena-wasm-binding/lib.execute.func1(0x30?, {0x40063e6000?, 0x30?, 0x1?}, {0x400133df88?, 0x4000ed43e8?, 0x4000a89d28?}, {0x4007026ea0?, 0x0?, 0x4000ed43e8?}, ...)
Mar  6 09:33:10 pi-server idena-node[214203]: #011/go/pkg/mod/github.com/idena-network/idena-wasm-binding@v0.0.0-20230304132014-3de89da5e128/lib/lib.go:75 +0x28c fp=0x4000a89c30 sp=0x4000a89810 pc=0x227345c
Mar  6 09:33:10 pi-server idena-node[214203]: github.com/idena-network/idena-wasm-binding/lib.execute(0x4005c4b908?, {0x40063e6000, 0xaa0d, 0xaa0d}, {0x400133df88, 0x8, 0x8}, {0x4007026ea0, 0x25, 0x30}, ...)
Mar  6 09:33:10 pi-server idena-node[214203]: #011/go/pkg/mod/github.com/idena-network/idena-wasm-binding@v0.0.0-20230304132014-3de89da5e128/lib/lib.go:75 +0x13c fp=0x4000a89d30 sp=0x4000a89c30 pc=0x2272ffc
Mar  6 09:33:10 pi-server idena-node[214203]: github.com/idena-network/idena-wasm-binding/lib.Execute(0x4007e4dee0?, {0x40063e6000, 0xaa0d, 0xaa0d}, {0x400133df58?, 0x30?}, {0x4008d75830, 0x2, 0x2}, {0xa8, ...}, ...)
Mar  6 09:33:10 pi-server idena-node[214203]: #011/go/pkg/mod/github.com/idena-network/idena-wasm-binding@v0.0.0-20230304132014-3de89da5e128/lib/lib.go:61 +0xcc fp=0x4000a89e00 sp=0x4000a89d30 pc=0x2272d5c
```

**Comment by illusiontorment** [comment]
Could this be an issue?
![image](https://user-images.githubusercontent.com/39781336/223059255-e24a6569-3192-4cff-927c-4678d400fa37.png)

**Comment by hunagyp** [comment]
rc2 just crashed and auto restarted

```
Mar  6 09:39:55 pi-server idena-node[214248]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/s
rc/emitter_arm64.rs:1442:18
Mar  6 09:39:55 pi-server idena-node[214248]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar  6 09:39:55 pi-server idena-node[214248]: fatal runtime error: failed to initiate panic, error 1409425984
Mar  6 09:39:55 pi-server idena-node[214248]: SIGABRT: abort
Mar  6 09:39:55 pi-server idena-node[214248]: PC=0xffffb042f200 m=10 sigcode=18446744073709551610
Mar  6 09:39:55 pi-server idena-node[214248]: signal arrived during cgo execution
Mar  6 09:39:55 pi-server idena-node[214248]: goroutine 2940 [syscall]:
Mar  6 09:39:55 pi-server idena-node[214248]: runtime.cgocall(0x2319050, 0x400572f818)
Mar  6 09:39:55 pi-server idena-node[214248]: #011/usr/local/go/src/runtime/cgocall.go:158 +0x54 fp=0x400572f6c0 sp=0x400572f680 pc=0x1001084
Mar  6 09:39:55 pi-server idena-node[214248]: github.com/idena-network/idena-wasm-binding/lib._Cfunc_execute({0x400bba7b90, 0x40066b6730, {0x2317ec8, 0x2317f30, 0x2317fc8, 0x2318050, 0x2318140, 0x23180d0, 0x23181b0, 0x
2318220, ...}}, ...)
Mar  6 09:39:55 pi-server idena-node[214248]: #011_cgo_gotypes.go:393 +0x40 fp=0x400572f810 sp=0x400572f6c0 pc=0x226dbe0
Mar  6 09:39:55 pi-server idena-node[214248]: github.com/idena-network/idena-wasm-binding/lib.execute.func1(0x30?, {0x4003866000?, 0x30?, 0x1?}, {0x40066b6750?, 0x40066b6800?, 0x400572fd28?}, {0x40084f17a0?, 0x0?, 0x40
066b6800?}, ...)
```

**Comment by sidenaio** [comment]
@hunagyp, please show your output of ```hostnamectl``` command

**Comment by hunagyp** [comment]
> @hunagyp, please show your output of `hostnamectl` command

```
ubuntu@pi-server:~/idena-go$ hostnamectl
 Static hostname: pi-server
 Pretty hostname: hi-fi-pi
       Icon name: computer
      Machine ID: 7d513a26e61e4cc7a0bf525ec264fd63
         Boot ID: c0d765eaac9042e6b3acf7e6b8a917b3
Operating System: Ubuntu 22.04.2 LTS
          Kernel: Linux 5.15.0-1024-raspi
    Architecture: arm64

```

**Comment by hunagyp** [comment]
crashes so far (just for timestamps...)

```
ubuntu@pi-server:~/idena-go$ date
Mon Mar  6 10:37:16 CET 2023

ubuntu@pi-server:~/idena-go$ sudo grep unnamed /var/log/syslog
---- rc1
Mar  6 09:01:04 pi-server idena-node[210088]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /home/hugo/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
Mar  6 09:05:17 pi-server idena-node[213783]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /home/hugo/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
Mar  6 09:09:38 pi-server idena-node[213819]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /home/hugo/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
Mar  6 09:13:40 pi-server idena-node[213900]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /home/hugo/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
Mar  6 09:17:51 pi-server idena-node[213941]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /home/hugo/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
Mar  6 09:21:49 pi-server idena-node[213982]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /home/hugo/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
---- rc2
Mar  6 09:29:15 pi-server idena-node[214130]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
Mar  6 09:33:10 pi-server idena-node[214203]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
Mar  6 09:39:55 pi-server idena-node[214248]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
Mar  6 10:33:22 pi-server idena-node[214350]: thread '<unnamed>' panicked at 'singlepass can't emit ROR S64 GPR(X9) Imm64(32) GPR(X9)', /cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:1442:18
```

**Comment by sidenaio** [comment]
Looks like a bug in wasmer. I've opened an [issue](https://github.com/wasmerio/wasmer/issues/3647).

**Comment by kikimanito** [comment]
Hi, the fix seem to be done on wasmer side: https://github.com/wasmerio/wasmer/issues/3647, any instructions on how to proceed?

**Comment by sidenaio** [comment]
Now we have to update wasmer to 3.x. I'm working on it.

**Comment by sidenaio** [comment]
@hunagyp @kikimanito @illusiontorment @biterminator, please try https://github.com/idena-network/idena-go/releases/tag/v1.0.2-rc3

**Comment by kikimanito** [comment]
Thanks, so far it is working, although it's been only for 20 minutes. In case it is helpful, I'm pasting a couple of errors that I can see in logs, but the node seems to be running just fine:
```log
ERROR[03-16|20:48:15.186] Post consuming error                     component=downloader err="preliminary head is lower than manifest's head"
ERROR[03-16|20:50:18.116] contract err                             err="Out of gas"
ERROR[03-16|20:50:19.863] contract err                             err="Out of gas"
ERROR[03-16|20:56:24.985] error while writing to stream            id=QmQRueyzM1AaAUGKBN5CQgxAgTbJFyxHE8ygLP4F94JkTR err="stream reset"
```

**Comment by sidenaio** [comment]
> 

It's ok.

**Comment by hunagyp** [comment]
i started the new node and will monitor it, thank you! (although i'm currently in suspended status so i guess i will not mine anything...)

**Comment by kikimanito** [comment]
11h of node running and mining, no issues so far. Thanks again.

**Comment by HaroldSP** [comment]
Yep, works fine up till now
