### ISSUE TITLE
panic: rlp: cannot encode negative *big.Int

### ISSUE THREAD

**Issue by Endogen** [idena-network/idena-go#358]
this request leads to an exception that will shutdown the node

```
{
  "method": "dna_sendTransaction",
  "params": [
    {
      "from": "0xcaff4f51e73639d7426a98adf5c53ffaa02f49e5",
      "to": "0x18a5eb84dc215a2f170ff1f78dc1873ed8d04d74",
      "amount": "-10000000000000000000000000000000000"
    }
  ],
  "id": 5,
  "key": "some_key"
}
{
  "jsonrpc": "2.0",
  "id": 5,
  "result": "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
}
```
node log
```
panic: rlp: cannot encode negative *big.Int

goroutine 273928 [running]:
github.com/idena-network/idena-go/protocol.makeMsg(0x5, 0x50c0d00, 0xc00d08bf80, 0x0, 0xc000c09e78, 0x4042ff4)
        /Users/travis/gopath/src/github.com/idena-network/idena-go/protocol/peer.go:155 +0x188
github.com/idena-network/idena-go/protocol.(*protoPeer).broadcast.func1(0xc00abf5c00, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/idena-network/idena-go/protocol/peer.go:99 +0x6f
github.com/idena-network/idena-go/protocol.(*protoPeer).broadcast(0xc003b222a0)
        /Users/travis/gopath/src/github.com/idena-network/idena-go/protocol/peer.go:143 +0x26b
created by github.com/idena-network/idena-go/protocol.(*IdenaGossipHandler).runPeer
        /Users/travis/gopath/src/github.com/idena-network/idena-go/protocol/gossip.go:374 +0x7f5
```

**Comment by ridenaio** [comment]
This issue influences only on your local node, but panic is not a good way to handle this. An additional check will be added to prevent panics.
