### ISSUE TITLE
Err: cannot allocate memory

### ISSUE THREAD

**Issue by 0n0t0le** [idena-network/idena-go#567]
After today's update (0.22.0) and restart of the node, it constantly crashes with the following error:

```
INFO [09-23|14:01:28.188] Ipfs initialized                         peerId=QmPur1tYvpovvxiNEyJDhpPiXNwiKaPC6oCQyu67rT4MdZ
WARN [09-23|14:01:28.192] cannot parse subscriptions.json          err="unexpected end of JSON input"
panic: <memcall> could not acquire lock on 0x7fc404006000, limit reached? [Err: cannot allocate memory]

goroutine 1 [running]:
github.com/awnumar/memguard/core.Panic(0x1dd1580, 0xc0034b7480)
        /home/travis/gopath/pkg/mod/github.com/awnumar/memguard@v0.22.2/core/exit.go:86 +0x3a
github.com/awnumar/memguard/core.NewBuffer(0x20, 0xc000dd5560, 0x20, 0x20)
        /home/travis/gopath/pkg/mod/github.com/awnumar/memguard@v0.22.2/core/buffer.go:75 +0x343
github.com/awnumar/memguard.NewBuffer(0x20, 0xc0030d0fa0)
        /home/travis/gopath/pkg/mod/github.com/awnumar/memguard@v0.22.2/buffer.go:47 +0x2f
github.com/awnumar/memguard.NewBufferFromBytes(0xc000dd5560, 0x20, 0x20, 0x20)
        /home/travis/gopath/pkg/mod/github.com/awnumar/memguard@v0.22.2/buffer.go:61 +0x2f
github.com/idena-network/idena-go/secstore.(*SecStore).AddKey(...)
        /home/travis/gopath/src/github.com/idena-network/idena-go/secstore/secure_store.go:29
github.com/idena-network/idena-go/node.(*Node).StartWithHeight(0xc0004627e0, 0x0)
        /home/travis/gopath/src/github.com/idena-network/idena-go/node/node.go:229 +0x7f
github.com/idena-network/idena-go/node.(*Node).Start(...)
        /home/travis/gopath/src/github.com/idena-network/idena-go/node/node.go:225
main.main.func1(0xc00037c9a0, 0x0, 0xc000179a20)
        /home/travis/gopath/src/github.com/idena-network/idena-go/main.go:91 +0x394
github.com/urfave/cli.HandleAction(0x1d7f020, 0x22ac170, 0xc00037c9a0, 0xc00037c9a0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x11a
github.com/urfave/cli.(*App).Run(0xc00032c700, 0xc000138000, 0x5, 0x5, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:288 +0x649
main.main()
        /home/travis/gopath/src/github.com/idena-network/idena-go/main.go:96 +0x67e
runtime: note: your Linux kernel may be buggy
runtime: note: see https://golang.org/wiki/LinuxKernelSignalVectorBug
runtime: note: mlock workaround for kernel bug failed with errno 12
```

Server characteristics: 3 VCPU, 4Gb RAM, 80Gb SSD, Ubuntu 20.04. This server has 2 nodes in docker containers. Restarting and building again doesn't help. Everything worked correctly before the update

**Comment by serdrdoor** [comment]
Exactly the same error on Ubuntu 20.04. Server characteristic: 16VCPUS, 32Gb RAM, 320Gb SSD. But for ubuntu 18.04 all OK.

**Comment by ridenaio** [comment]
Hi, sorry for the late answer, does this problem still exist?
