### ISSUE TITLE
crash on mac

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-go#646]
a friend of mine tries running idena on the mac - in the desktop app we see:

![Selection_015](https://user-images.githubusercontent.com/111600/110646612-58939f80-81b7-11eb-90c2-3c0a9277980d.png)

on the console running just the node there is this error:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin

  Referenced from: /Users/Jim/Downloads/./idena-node-mac-0.24.3

  Expected in: flat namespace


dyld: Symbol not found: ____chkstk_darwin

  Referenced from: /Users/Jim/Downloads/./idena-node-mac-0.24.3

  Expected in: flat namespace


SIGABRT: abort

PC=0xbe579ee m=0 sigcode=0

signal arrived during cgo execution


goroutine 1 [syscall, locked to thread]:

runtime.cgocall(0x50f3ce0, 0xc0001c7eb0, 0x56da883)

/Users/runner/hostedtoolcache/go/1.14.15/x64/src/runtime/cgocall.go:133 +0x5b fp=0xc0001c7e80 sp=0xc0001c7e48 pc=0x400746b

github.com/idena-network/idena-go/crypto/secp256k1._Cfunc_secp256k1_context_create_sign_verify(0x0)

_cgo_gotypes.go:155 +0x4a fp=0xc0001c7eb0 sp=0xc0001c7e80 pc=0x429af3a

github.com/idena-network/idena-go/crypto/secp256k1.init.1()

/Users/runner/work/idena-go/idena-go/crypto/secp256k1/secp256.go:37 +0x22 fp=0xc0001c7ec8 sp=0xc0001c7eb0 pc=0x429dae2

runtime.doInit(0x68cb180)

/Users/runner/hostedtoolcache/go/1.14.15/x64/src/runtime/proc.go:5480 +0x8a fp=0xc0001c7ef8 sp=0xc0001c7ec8 pc=0x404867a

runtime.doInit(0x68d7480)

/Users/runner/hostedtoolcache/go/1.14.15/x64/src/runtime/proc.go:5475 +0x57 fp=0xc0001c7f28 sp=0xc0001c7ef8 pc=0x4048647

runtime.doInit(0x68d46a0)

/Users/runner/hostedtoolcache/go/1.14.15/x64/src/runtime/proc.go:5475 +0x57 fp=0xc0001c7f58 sp=0xc0001c7f28 pc=0x4048647

runtime.doInit(0x68cf920)

/Users/runner/hostedtoolcache/go/1.14.15/x64/src/runtime/proc.go:5475 +0x57 fp=0xc0001c7f88 sp=0xc0001c7f58 pc=0x4048647

runtime.main()

/Users/runner/hostedtoolcache/go/1.14.15/x64/src/runtime/proc.go:190 +0x1b6 fp=0xc0001c7fe0 sp=0xc0001c7f88 pc=0x403b9f6

runtime.goexit()

/Users/runner/hostedtoolcache/go/1.14.15/x64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001c7fe8 sp=0xc0001c7fe0 pc=0x406a011


rax    0x2000209

rbx    0x4

rcx    0x7fff5fbfe978

rdx    0x7fff5fbfedf0

rdi    0x6

rsi    0x4

rbp    0x7fff5fbfe9d0

rsp    0x7fff5fbfe978

r8     0x7fff5fbfe9f0

r9     0x0

r10    0x62

r11    0x246

r12    0x62

r13    0x7fff5fbfedf0

r14    0x6

r15    0x0

rip    0xbe579ee

rflags 0x246

cs     0x7

fs     0x0

gs     0x0
```

**Comment by ligi** [comment]
Ah @rioda-org helped me in the chat and it seems the minimum is mac os catalina but he runs Sierra (10.12.6).
Would be good if the errors would state this.
