### ISSUE TITLE
Segmentation fault with node v0.25.0

### ISSUE THREAD

**Issue by nonatomiclabs** [idena-network/idena-go#656]
Launching my node terminated after a while with a segfault:

~~~plain
INFO [03-23|08:11:35.186] Wait for block proposal 
INFO [03-23|08:11:35.186] Reduction started                        block=0xfda243a84d4521fde4d5b7582270ace3b5942378f3f19ac223fb24763133337c
INFO [03-23|08:11:35.190] Reduction completed                      block=0xfda243a84d4521fde4d5b7582270ace3b5942378f3f19ac223fb24763133337c isEmpty=false
INFO [03-23|08:11:35.191] binaryBa started                         block=0xfda243a84d4521fde4d5b7582270ace3b5942378f3f19ac223fb24763133337c
INFO [03-23|08:11:35.414] Reached FINAL                            block=0xfda243a84d4521fde4d5b7582270ace3b5942378f3f19ac223fb24763133337c txs=0
INFO [03-23|08:11:35.414] Node is synchronized                     component=downloader
INFO [03-23|08:11:41.001] Start loop                               round=2639564 head=0xfda243a84d4521fde4d5b7582270ace3b5942378f3f19ac223fb24763133337c peers=6 online-nodes=5089 network=6204
INFO [03-23|08:11:51.001] Selected proposer                        proposer=0x7983F70F2a807DE6Bf5A89C013d9ab002721d329
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x508387d]

goroutine 1071 [running]:
github.com/idena-network/idena-go/blockchain.(*Blockchain).calculateFlags(0xc00c1282a0, 0x0, 0xc007a865c0, 0xc004791eb0, 0x6d39d622e1c7afd8)
	/Users/runner/work/idena-go/idena-go/blockchain/blockchain.go:1423 +0x7d
github.com/idena-network/idena-go/blockchain.(*Blockchain).generateEmptyBlock(0xc00c1282a0, 0x0, 0xc004791eb0, 0x5a56e00)
	/Users/runner/work/idena-go/idena-go/blockchain/blockchain.go:355 +0x2d2
github.com/idena-network/idena-go/blockchain.(*Blockchain).GenerateEmptyBlock(0xc00c1282a0, 0x564e552)
	/Users/runner/work/idena-go/idena-go/blockchain/blockchain.go:366 +0x66
github.com/idena-network/idena-go/consensus.(*Engine).loop(0xc00b1b8d80)
	/Users/runner/work/idena-go/idena-go/consensus/engine.go:227 +0x8de
created by github.com/idena-network/idena-go/consensus.(*Engine).Start
	/Users/runner/work/idena-go/idena-go/consensus/engine.go:100 +0x28f
~~~

**System:** macOS v10.15.7
**Node version:** 0.25.0

**Comment by mnz2000** [comment]
Looks like I encountered the same issue on node 0.27.2:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e0cd14]
goroutine 16065 [running]:
github.com/idena-network/idena-go/blockchain.(*Blockchain).calculateFlags(0xc001c5ae10, 0x0, 0xc0073bea40, 0xc004c806b0, 0xf51fde778e08eea)
        /home/runner/work/idena-go/idena-go/blockchain/blockchain.go:1694 +0x74
github.com/idena-network/idena-go/blockchain.(*Blockchain).generateEmptyBlock(0xc001c5ae10, 0x0, 0xc004c806b0, 0x0, 0x0, 0xc01e47b9e0, 0xc005c56a90)
        /home/runner/work/idena-go/idena-go/blockchain/blockchain.go:383 +0x2ec
github.com/idena-network/idena-go/blockchain.(*Blockchain).GenerateEmptyBlock(0xc001c5ae10, 0x1a)
        /home/runner/work/idena-go/idena-go/blockchain/blockchain.go:394 +0x6e
github.com/idena-network/idena-go/consensus.(*Engine).reduction(0xc005d966c0, 0x35137b, 0xc01efd2e00, 0x94b91f9bf, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/idena-go/idena-go/consensus/engine.go:366 +0x42e
github.com/idena-network/idena-go/consensus.(*Engine).loop(0xc005d966c0)

```

More details from output.log:

```
ERROR[10-09|15:43:55.802] goroutine 5095532 [running]:
github.com/idena-network/idena-go/rpc.(*Server).serveRequest.func1(0xc0044d22c0, 0x278d258, 0xc025c3d360)
        /home/runner/work/idena-go/idena-go/rpc/server.go:133 +0x128
panic(0x1fdc880, 0xc019ce3dd0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/panic.go:965 +0x1b9
github.com/cosmos/iavl.(*nodeDB).GetNode(0xc01e7c4780, 0xc00d201ae0, 0x20, 0x20, 0x0)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/nodedb.go:88 +0x779
github.com/cosmos/iavl.(*Node).getRightNode(...)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:430
github.com/cosmos/iavl.(*Node).get(0xc025b47040, 0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0x22, 0x1, 0x70, 0xc01e7c4780)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:175 +0x2f6
github.com/cosmos/iavl.(*Node).get(0xc025b46fa0, 0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0x22, 0x1, 0xc019f9c420, 0xc01e7c4780)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:176 +0x273
github.com/cosmos/iavl.(*Node).get(0xc025b46f00, 0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0x1d, 0x1, 0xc019f9c420, 0xc01e7c4780)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:176 +0x273
github.com/cosmos/iavl.(*Node).get(0xc004336280, 0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0x15, 0x1, 0xc019f9c420, 0xc01e7c4780)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:176 +0x273
github.com/cosmos/iavl.(*Node).get(0xc0043361e0, 0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0x15, 0x1, 0xc019f9c420, 0xc01e7c4780)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:176 +0x273
github.com/cosmos/iavl.(*Node).get(0xc004336140, 0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0x15, 0x1, 0x0, 0xc01e7c4780)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:176 +0x273
github.com/cosmos/iavl.(*Node).get(0xc0043360a0, 0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0x15, 0x1, 0x0, 0xc01e7c4780)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:176 +0x273
github.com/cosmos/iavl.(*Node).get(0xc004336000, 0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0x15, 0x1, 0x50, 0xc0041ae640)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:176 +0x273
github.com/cosmos/iavl.(*Node).get(0xc003f0bea0, 0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0x1d70fe9, 0xc001cf08d0, 0x7f66e2538ce8, 0x28)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:176 +0x273
github.com/cosmos/iavl.(*ImmutableTree).Get(0xc00ea65ed8, 0x3625eec, 0x1, 0x1, 0xc001cf0900, 0x1d80b06, 0xc0125ec8e8, 0x28)
        /home/runner/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/immutable_tree.go:153 +0x5a
github.com/idena-network/idena-go/core/state.(*MutableTree).Get(0xc002c54c20, 0x3625eec, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/idena-go/idena-go/core/state/tree.go:116 +0xb4
github.com/idena-network/idena-go/core/state.(*StateDB).getStateDelayedOfflinePenalty(0xc0125ec840, 0xc0041ae6cc)
        /home/runner/work/idena-go/idena-go/core/state/statedb.go:785 +0xb5
github.com/idena-network/idena-go/core/state.(*StateDB).GetOrNewDelayedOfflinePenaltyObject(0xc0125ec840, 0x5882e88bc045ed09)
        /home/runner/work/idena-go/idena-go/core/state/statedb.go:886 +0x2b
github.com/idena-network/idena-go/core/state.(*StateDB).HasDelayedOfflinePenalty(0xc0125ec840, 0x5882e88bc045ed09, 0x8e71d0f7d359dde1, 0x8875863e, 0xb41300000)
        /home/runner/work/idena-go/idena-go/core/state/statedb.go:1595 +0x2b
github.com/idena-network/idena-go/api.convertIdentity(0xe88bc045ed09004b, 0xd0f7d359dde15882, 0x8e718875863e8e71, 0x0, 0x0, 0x0, 0xc00bbd06c0, 0x700490000, 0x0, 0xc00b2fdcc0, ...)
        /home/runner/work/idena-go/idena-go/api/dna_api.go:428 +0x7af
github.com/idena-network/idena-go/api.(*DnaApi).Identity(0xc006d0f5c0, 0xc025cbcf70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/idena-go/idena-go/api/dna_api.go:350 +0x2f8
reflect.Value.call(0xc001a89200, 0xc0036b25d0, 0x13, 0x231897c, 0x4, 0xc025c6a1b0, 0x2, 0x2, 0xc025c6a1c8, 0xc025c3ad80, ...)
        /opt/hostedtoolcache/go/1.16.8/x64/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc001a89200, 0xc0036b25d0, 0x13, 0xc025c6a1b0, 0x2, 0x2, 0x1, 0x2, 0xc025c3ad68)
        /opt/hostedtoolcache/go/1.16.8/x64/src/reflect/value.go:337 +0xb9
github.com/idena-network/idena-go/rpc.(*Server).handle(0xc0044d22c0, 0x27793d8, 0xc025c315c0, 0x278d258, 0xc025c3d360, 0xc01c313da0, 0xc01c313d70, 0x0, 0x2058c00)
        /home/runner/work/idena-go/idena-go/rpc/server.go:310 +0x69b
github.com/idena-network/idena-go/rpc.(*Server).exec(0xc0044d22c0, 0x27793d8, 0xc025c315c0, 0x278d258, 0xc025c3d360, 0xc01c313da0)
        /home/runner/work/idena-go/idena-go/rpc/server.go:331 +0x1ca
github.com/idena-network/idena-go/rpc.(*Server).serveRequest(0xc0044d22c0, 0x2779480, 0xc025c6a120, 0x278d258, 0xc025c3d360, 0xc019ce3c01, 0x1, 0x0, 0x0)
        /home/runner/work/idena-go/idena-go/rpc/server.go:193 +0x425
github.com/idena-network/idena-go/rpc.(*Server).ServeSingleRequest(...)
        /home/runner/work/idena-go/idena-go/rpc/server.go:224
github.com/idena-network/idena-go/rpc.(*Server).ServeHTTP(0xc0044d22c0, 0x2771a90, 0xc0259c6700, 0xc025b3b200)
        /home/runner/work/idena-go/idena-go/rpc/http.go:253 +0x7c5
github.com/rs/cors.(*Cors).Handler.func1(0x2771a90, 0xc0259c6700, 0xc025b3b200)
        /home/runner/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc007074be0, 0x2771a90, 0xc0259c6700, 0xc025b3b200)
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:2049 +0x44
github.com/idena-network/idena-go/rpc.(*virtualHostHandler).ServeHTTP(0xc004d3f170, 0x2771a90, 0xc0259c6700, 0xc025b3b200)
        /home/runner/work/idena-go/idena-go/rpc/http.go:322 +0x142
net/http.serverHandler.ServeHTTP(0xc000262d20, 0x2771a90, 0xc0259c6700, 0xc025b3b200)
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc025b46c80, 0x2779480, 0xc025c30940)
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:2993 +0x39b

```

System: Debian 9.13 on Hetzner CPX21 VPS (3 vCPU's and 4 GB RAM).

The segfault happened after I had just updated to the new node version 0.27.2. The new version ran about 16 minutes before the segfault. Before that, node 0.27.1 had crashed once with a "too many open files" error, which I fixed by updating ulimit -n from 1024 files to 65535 files. It is thus possible that something was left corrupted inside datadir.
